name: Test or Release

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test-or-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Install Dependencies
      run: pnpm i --frozen-lockfile --no-verify-store-integrity
    - name: Test
      run: pnpm -r test && pnpm test
    - name: Publish
      if: github.ref_name == 'master'
      run: pnpm -r --workspace-concurrency=1 exec -- semantic-release -e semantic-release-monorepo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
